[package]

# Semantic Versioning is used: https://semver.org/
version = "2.3.2"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Booster_T1"
author = "Ziqi Fan"
maintainer = "Ziqi Fan"
description = "Booster T1 locomotion tasks for Isaac Lab."
repository = ""
keywords = ["extension", "Booster_T1", "booster_t1", "isaaclab", "locomotion"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "Booster_T1"

[isaac_lab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
