# Copyright (c) 2024-2026 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

x-default-Booster-T1-environment: &default-Booster-T1-environment
  - OMNI_KIT_ALLOW_ROOT=1

x-default-Booster-T1-deploy: &default-Booster-T1-deploy
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  Booster-T1:
    env_file: .env.base
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - ISAACLAB_BASE_IMAGE_ARG=${ISAACLAB_BASE_IMAGE}
        - DOCKER_ISAACLAB_EXTENSION_TEMPLATE_PATH_ARG=${DOCKER_ISAACLAB_EXTENSION_TEMPLATE_PATH}
    image: Booster-T1
    container_name: Booster-T1
    volumes:
      - type: bind
        source: ../
        target: ${DOCKER_ISAACLAB_EXTENSION_TEMPLATE_PATH}
    network_mode: host
    environment: *default-Booster-T1-environment
    deploy: *default-Booster-T1-deploy
    # This is the entrypoint for the container
    entrypoint: bash
    stdin_open: true
    tty: true
